<template>
  <v-container class="">
       <h1 style="text-align:center;"> Mobil Serv IIoT Insights platform user Terms & Conditions </h1>
       <ol>
          <li>By accepting these Terms and Conditions (T&C) for using Mobil Mobil Serv IIoT Insights digital platform (Mobil Serv IIoT Insights Platform) each user agrees to adhere and bound by the T&C of using the Mobil Serv IIoT Insights Platform. Each user understands and agrees that the continuity and validity of his / her access to the Mobil Serv IIoT Insights Platform is subject to the T&C laid  hereof.</li>
          <li>ExxonMobil Lubricants Pvt. Ltd. (EMLPL/ExxonMobil) having its registered office at 1st Main Road, Whitefield Main Road, 5th Floor, Prestige Shantiniketan Complex Road, Bengaluru, Karnataka 560048 may suspend or terminate the user access of Mobil Serv IIoT Insights Platform at any time it deems necessary without having any liability/ consequences whatsoever towards any user and without assigning any reasons thereof and without giving any notice to any user, whatsoever.</li>
          <li>Using the Mobil Serv IIoT Insights Platform is voluntary for any user.</li>
          <li>EMLPL reserves the right to refuse Mobil Serv IIoT Insights Platform access or modify, amend, change, either retrospectively or prospectively, these T&C governing the Mobil Serv IIoT Insights Platform at its sole discretion without assigning any reason.</li>
          <li>Users acknowledge that EMLPL may select users to grant access to the Mobil Serv IIoT Insights Platform at its sole discretion and the validity of the access is at the sole discretion of EMLPL.</li>
          <li>EMLPL has the right to add, amend, modify or make any change in the Mobil Serv IIoT Insights Platform, as it deems necessary without having any liability / consequences whatsoever, at any time, at its sole discretion. The Mobil Serv IIoT Insights Platform is subject to any force majeure condition.</li>
          <li>Any misrepresentation, misstatement or non-conformance of the Mobil Serv IIoT Insights Platform T&C, in any manner whatsoever, by user shall be liable for cancellation of their access to Mobil Serv IIoT Insights Platform. EMLPL reserves the right to take appropriate legal action against such user to recover damages, including its attorney fees, incurred in any legal action or otherwise.</li>
          <li>Mobil Serv IIoT Insights Platform access guidelines:</li>
          <ul>
            <li>In order to receive timely information, the user must ensure that his/ her contact details are up to date on Mobil Serv IIoT Insights Platform.</li>
            <li>user acknowledges that he/she is over 18 years of age, of sound mind, not a declared insolvent and have not been convicted of any offence involving moral turpitude.</li>
            <li>user warrants that he/she has all legal, moral, and other rights that may be necessary to publish the information;</li>
            <li>user acknowledges and agrees that ExxonMobil shall have the right (but not obligation), at its sole discretion, to refuse to publish or to remove or block access to any content provided at any time and for any reason, with or without notice to the user and that ExxonMobil shall the right to assimilate, collect, reproduce and use the information provided by the user in any manner we deem fit.</li>
            <li>Users are solely responsible for updating their respective login ID and password confidential. Any fraud resulting due to this confidentiality being compromised will be held against the user only.</li>
          </ul>
          <li>Information Utilization:</li>
          <ul>
            <li>Each user agrees and admits that he/she has provided their personal information/ details (such as name, email id , contact number) voluntarily and knowingly to EMLPL and/or EMLPL representative and/or on Mobil Serv IIoT Insights Platform. The users have no objection, whatsoever of the user details and information being used for the purposes of this Mobil Serv IIoT Insights Platform and accordingly the same being complied and saved on the Mobil Serv IIoT Insights Platform server.</li>
            <li>Users agree that the information submitted for the Mobil Serv IIoT Insights Platform may be retained and used by EMLPL and the users agree that EMLPL may use the data to contact and provide updates about EMLPL s products and promotions from time to time.</li>
            <li>Users agree that the information submitted on the Mobil Serv IIoT Insights Platform is solely discretionary and does not contain any confidential data, and can be used by EMLPL. Users agree that any claims arising further to this regard, will be solely their responsibility. EMLPL will not be responsible for any disputes arising with respect to the same.</li>
            <li>Users understand that under some limited circumstances, EMLPL may be required by law to disclose their personal information and any other submitted information by them. Users thereby authorize EMLPL or its affiliates in this regard.</li>
            <li>User need to sign up for a user account by providing all required information in order to access or use the Mobil Serv IIoT Insights Platform. If user represent an organization and wish to use the Mobil Serv IIoT Insights Platform for corporate use, we recommend that user, sign up for user accounts by providing your corporate contact information. In particular, we recommend that user use its corporate email address.</li>
          </ul>
          <li>Each user of this Mobil Serv IIoT Insights Platform represents and warrants that it understands and is in agreement and wilfully comply with applicable laws and regulations regarding anticorruption, bribery or any other law related to usage of the Mobil Serv IIoT Insights Platform and data.</li>
          <li>
            Limitation of Liability: In no event shall EMLPL or its representatives be liable to any user for any damages whatsoever including direct, special, punitive, indirect, incidental, consequential damages due to misuse of the Mobil Serv IIoT Insights Platform or any of the benefits forming part thereof.
            <br>
            The hardware installed at site to read data for Mobil Serv IIoT Insights are manufactured by a third party manufacturer which is not associated with and/or related to ExxonMobil Lubricants Private Limited and/or any of its affiliates (ExxonMobil). The decision to purchase the platform offer and accessories is solely at your discretion and risk. While purchasing and using the hardware and software you explicitly agree that ExxonMobil shall not be liable for any loss and/or damages (including special, indirect or consequential damages) of any nature whatsoever to your machine or otherwise resulting from the use of any sensor. Any kind of warranty of the hardware in relation to performance and otherwise is attributable to the manufacturer and required to be discussed with the manufacturer by the user and purchaser of Mobil Serv IIoT insights offer”.
          </li>
          <li>Indemnification. User agrees to indemnify, defend and hold harmless ExxonMobil, its officers, directors, employees, agents, suppliers and third party partners from and against all losses, expenses, damages and costs, including reasonable attorneys' fee, resulting from any violation by user of these T&C.</li>
          <li>Disclaimer of Warranties You expressly understand and agree that the use of the services is at your sole risk. The services are provided on an as-is-and-as-available basis.</li>
          <li>ExxonMobil expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose. ExxonMobil makes no warranty that the services will be uninterrupted, timely, secure, or error free. Use of any material downloaded or obtained through the use of the services/ Mobil Serv IIoT Insights Platform shall be at your own discretion and risk and you will be solely responsible for any damage to your computer system, mobile telephone, wireless device or data that results from the use of the services or the download of any such material.</li>
          <li>Privacy. ExxonMobil respects the privacy of its website users. Please refer to both mobil.co.in Privacy Policy and your organization's Privacy Policy, as applicable, for users' rights and responsibilities with respect to information that is disclosed on Mobil Serv IIoT Insights Platform. Users understand that under some limited circumstances, ExxonMobil may be required by law to disclose their personal information and any other submitted information by them. Participants thereby authorize ExxonMobil or its affiliates in this regard. Any personal data relating to entrants will be used solely in accordance with current India data protection legislation and best practice. Please see the mobil.co.in Privacy Policy for further details.</li>
          <li>Confidential Information. Subject to any applicable terms and conditions set forth in our Privacy Policy, your Privacy Policy, or any non-disclosure agreements, any communication or other material that you submit or post via this Mobil Serv IIoT Insights Platform will not be deemed to be confidential information unless so specified by ExxonMobil in advance.</li>
          <li>Trademarks. All ExxonMobil product names, whether or not appearing in large print or with the trademark symbol, are trademarks of ExxonMobil, its affiliates, related companies or its licensors or joint venture partners, unless otherwise noted. The use or misuse of these trademarks or any other materials, except as permitted herein, is expressly prohibited and may be in violation of copyright law, trademark law, the law of privacy and publicity, and communications regulations and statutes. Please be advised that ExxonMobil actively and aggressively enforces its intellectual property rights to the fullest extent of the law. By submitting any trademarked Content via this Mobil Serv IIoT Insights Platform, you warrant and represent that you have all legal, moral, and other rights that may be necessary to publish, republish or distribute the content and will comply to any and all trademark law with respect to that content.</li>
          <li>Third Party Websites and Links. The content Mobil Serv IIoT Insights Platform may contain links or references to other websites maintained by your organization or by third parties over whom ExxonMobil has no control. ExxonMobil makes no warranties or representations of any kind as to the accuracy, currency, or completeness of any information contained in such websites and shall have no liability for any damages or injuries of any kind arising from such content or information. Inclusion of any external or third party link does not imply an endorsement or recommendation by ExxonMobil.</li>
          <li>Copyrights. The entire Contents of Mobil Serv IIoT Insights Platform are subject to copyright protection. Any ExxonMobil proprietary Content in Mobil Serv IIoT Insights Platform may not be copied other than for noncommercial individual reference with all copyright or other proprietary notices retained, and thereafter may not be recopied, reproduced or otherwise redistributed. Except as expressly provided above, you may not otherwise copy, display, download, distribute, modify, reproduce, republish or retransmit any information, text or documents contained in Mobil Serv IIoT Insights Platform or any portion thereof in any electronic medium or in hard copy, or create any derivative work based on such images, text or documents, without the express written consent of ExxonMobil. Nothing contained herein shall be construed as conferring by implication, estoppel or otherwise any license or right under any patent or trademark of ExxonMobil, or any third party. By submitting any copyrighted Content via Mobil Serv IIoT Insights Platform, you warrant and represent that you have all legal, moral, and other rights that may be necessary to publish, republish or distribute the Content and will comply to any and all copyright law with respect to that Content.</li>
          <li>Void Where Prohibited. Mobil Serv IIoT Insights Platform and its Contents are intended to comply with the laws and regulations in India. Although the information on Mobil Serv IIoT Insights Platform may be accessible to users outside of India, the information pertaining to ExxonMobil Catalog is intended for use only by residents of India. ExxonMobil reserves to right to limit provision of its products or services to any person, geographic region or jurisdiction and/or to limit the quantities or any products or services we provide. Any offer for any product or service made on Mobil Serv IIoT Insights Platform is void where prohibited.</li>
          <li>Governing Laws. This Terms of Use Agreement / T&C and your use of Mobil Serv IIoT Insights Platform shall be governed by the laws of India without regard to its conflicts of laws principles. Any legal action or proceeding related to these T&C of Mobil Serv IIoT Insights Platform shall be brought exclusively in a court at Bangalore.</li>
          <li>Miscellaneous. If any provision of this Terms of Use Agreement/ T&C is held to be unlawful, void or unenforceable, then such provision shall be severable without affecting the enforceability of all remaining provisions. ExxonMobil reserves the right to alter or delete materials from Mobil Serv IIoT Insights Platform at any time at its discretion. ExxonMobil may modify the T&C at any time through a service announcement or by sending email to your primary email address.</li>
          <li>Suspension and Termination ExxonMobil may suspend your user account or temporarily disable access to whole or part of any service in the event of any suspected illegal activity, extended periods of inactivity or requests by law enforcement or other government agencies.</li>

        </ol>
  </v-container>
</template>

<script>


export default {
 name: 'termsAndConditions'
};
</script>

<style scoped>
li{
  margin: 10px 0;
  text-align: justify;
}
.body {
  background: white;
}
</style>